Added personal stats stats selection
jgolla/torn-api pull request #419
Opened 2022-12-25 20:18 UTC by LeoMavri

2022-12-26 11:45 UTC, jgolla requested changes

2022-12-26 11:45 UTC, jgolla commented on lib/User.ts
> +import { TornAPI } from '.';
This is unused. Can we remove it?

2022-12-26 11:45 UTC, jgolla commented on test/User.test.ts
> +    it('personalstats', async () => {
Can we update the name of the test? Maybe some like `personalstats with specified stats`. Also, can we add a spot check on the return of the `personalstats` function to make sure the stats we want come back and more importantly a stat we do not want, does not get returned.

2022-12-26 11:45 UTC, jgolla commented on test/User.test.ts
> +    })
Missing a semicolon here. I think.

2022-12-27 21:04 UTC, LeoMavri commented
All issues have been resolved.

2022-12-29 12:30 UTC, jgolla approved these changes

2022-12-29 12:31 UTC, merged